/**
 * finance_reports.js
 * Interactive UI for monthly PTA finance reports with hierarchical drill-down.
 */
(function ($) {
    'use strict';

    var MONTHS = [
        '', 'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December'
    ];

    // ─── Helpers ───────────────────────────────────────────────────
    function ajax(params) {
        return $.ajax($.extend({
            url: FINANCE.ajaxUrl,
            dataType: 'json'
        }, params));
    }

    function showAlert(container, msg, type) {
        $(container).html(
            '<div class="alert alert-' + (type || 'info') + ' alert-dismissible fade show" role="alert">' +
            msg +
            '<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>' +
            '</div>'
        );
    }

    function formatCurrency(cents) {
        var dollars = (parseInt(cents, 10) || 0);
        return '$' + dollars.toLocaleString();
    }

    // ─── Reports List ──────────────────────────────────────────────
    function loadReportsList() {
        ajax({
            data: {action: 'list_reports'},
            success: function (res) {
                if (res.status !== 'success' || !res.data.length) {
                    $('#reports-list-container').html('<p class="text-muted">No reports generated yet. Use the <b>Generate Report</b> tab.</p>');
                    return;
                }
                var html = '<table class="table table-bordered table-hover table-sm" id="reports-list-table">' +
                    '<thead class="thead-light"><tr>' +
                    '<th>Month</th><th>Year</th><th>Generated At</th><th>Generated By</th>' +
                    '<th>Total Charges</th><th>Status</th><th>Actions</th>' +
                    '</tr></thead><tbody>';
                $.each(res.data, function (_, r) {
                    var genDate = r.generated_at ? new Date(r.generated_at * 1000).toLocaleString() : '';
                    html += '<tr>' +
                        '<td>' + MONTHS[r.report_month] + '</td>' +
                        '<td>' + r.report_year + '</td>' +
                        '<td>' + genDate + '</td>' +
                        '<td>' + (r.generated_by || '') + '</td>' +
                        '<td>' + formatCurrency(r.total_charges) + '</td>' +
                        '<td><span class="badge badge-' + (r.status === 'finalized' ? 'success' : 'warning') + '">' + r.status + '</span></td>' +
                        '<td>' +
                        '<button class="btn btn-xs btn-outline-primary btn-view-report mr-1" data-id="' + r.id + '" ' +
                        'data-month="' + r.report_month + '" data-year="' + r.report_year + '">' +
                        '<i class="fas fa-eye"></i> View</button>' +
                        '<a class="btn btn-xs btn-outline-success" href="' + FINANCE.downloadUrl + '&report_id=' + r.id + '" target="_blank">' +
                        '<i class="fas fa-download"></i> CSV</a>' +
                        '</td></tr>';
                });
                html += '</tbody></table>';
                $('#reports-list-container').html(html);
                $('#reports-list-table').DataTable({paging: false, info: false, searching: false, order: [[1, 'desc'], [0, 'desc']]});
            },
            error: function () {
                $('#reports-list-container').html('<p class="text-danger">Failed to load reports.</p>');
            }
        });
    }

    // ─── View / Drill-Down ─────────────────────────────────────────
    function viewReport(reportId, month, year) {
        $('#reports-list-container').hide();
        $('#report-detail-container').show();
        $('#report-detail-title').text(MONTHS[month] + ' ' + year + ' – EM Charges by PTA');
        $('#btn-download-csv').attr('href', FINANCE.downloadUrl + '&report_id=' + reportId);

        ajax({
            data: {action: 'get_report', report_id: reportId},
            success: function (res) {
                if (res.status !== 'success') {
                    showAlert('#report-drilldown', 'Could not load report.', 'danger');
                    return;
                }
                renderDrillDown(res.data, reportId);
            }
        });
    }

    function renderDrillDown(report, reportId) {
        var rd = report.report_data || {};
        var groups = rd.pta_groups || [];

        $('#report-summary').html(
            '<span class="badge badge-dark p-2 mr-2">Grand Total: ' + formatCurrency(rd.grand_total) + '</span>' +
            '<span class="badge badge-secondary p-2">PTAs: ' + groups.length + '</span>'
        );

        if (!groups.length) {
            $('#report-drilldown').html('<p class="text-muted">No charge data for this period.</p>');
            return;
        }

        var html = '<div class="accordion" id="ptaAccordion">';
        $.each(groups, function (gi, g) {
            var ptaId = 'pta-' + gi;
            html += '<div class="card mb-1">' +
                '<div class="card-header py-2 px-3 d-flex align-items-center drilldown-header" ' +
                'id="heading-' + ptaId + '" data-toggle="collapse" data-target="#collapse-' + ptaId + '" ' +
                'aria-expanded="false" style="cursor:pointer;">' +
                '<i class="fas fa-chevron-right mr-2 toggle-icon"></i>' +
                '<strong class="mr-auto">' + escapeHtml(g.pta_number) + '</strong>' +
                '<span class="badge badge-info ml-2">' + g.projects.length + ' project(s)</span>' +
                '<span class="badge badge-dark ml-2">' + formatCurrency(g.total_charges) + '</span>' +
                '</div>' +
                '<div id="collapse-' + ptaId + '" class="collapse" data-parent="#ptaAccordion">' +
                '<div class="card-body p-2">';

            // Projects inside this PTA
            html += '<div class="accordion" id="projAccordion-' + gi + '">';
            $.each(g.projects, function (pi, p) {
                var projId = ptaId + '-proj-' + pi;
                html += '<div class="card mb-1 ml-3">' +
                    '<div class="card-header py-1 px-3 d-flex align-items-center drilldown-header" ' +
                    'data-toggle="collapse" data-target="#collapse-' + projId + '" style="cursor:pointer;">' +
                    '<i class="fas fa-chevron-right mr-2 toggle-icon"></i>' +
                    '<span class="mr-auto">PID ' + p.project_id + ' – ' + escapeHtml(p.project_title) + '</span>' +
                    '<span class="badge badge-secondary ml-2">' + p.external_modules.length + ' EM(s)</span>' +
                    '<span class="badge badge-dark ml-2">' + formatCurrency(p.total_charges) + '</span>' +
                    '</div>' +
                    '<div id="collapse-' + projId + '" class="collapse" data-parent="#projAccordion-' + gi + '">' +
                    '<div class="card-body p-2 ml-3">';

                // EM detail table
                html += '<table class="table table-sm table-striped mb-0">' +
                    '<thead><tr><th>Module Prefix</th><th>Maintenance Fees</th><th>Instance</th></tr></thead><tbody>';
                $.each(p.external_modules, function (_, em) {
                    html += '<tr><td>' + escapeHtml(em.module_prefix) + '</td>' +
                        '<td>' + formatCurrency(em.maintenance_fees) + '</td>' +
                        '<td>' + escapeHtml(em.instance || '') + '</td></tr>';
                });
                html += '</tbody></table>';

                html += '</div></div></div>'; // close project card
            });
            html += '</div>'; // close projAccordion

            html += '</div></div></div>'; // close PTA card
        });
        html += '</div>';

        $('#report-drilldown').html(html);
    }

    function escapeHtml(s) {
        if (!s) return '';
        return $('<span>').text(s).html();
    }

    // ─── Generate ──────────────────────────────────────────────────
    function generateReport() {
        var month = $('#gen-month').val();
        var year  = $('#gen-year').val();
        var regen = $('#gen-regenerate').is(':checked') ? 1 : 0;
        $('#btn-generate').prop('disabled', true);
        ajax({
            type: 'POST',
            data: {action: 'generate_report', month: month, year: year, regenerate: regen},
            success: function (res) {
                if (res.status === 'success') {
                    var d = res.data;
                    var msg = 'Report generated.';
                    if (d.already_exists) msg = 'Report already exists for this month. Check "Regenerate" to overwrite.';
                    if (d.regenerated) msg = 'Report regenerated successfully.';
                    showAlert('#gen-feedback', msg, d.already_exists ? 'warning' : 'success');
                    loadReportsList();
                } else {
                    showAlert('#gen-feedback', res.message || 'Error', 'danger');
                }
            },
            error: function (xhr) {
                var msg = 'Server error';
                try { msg = JSON.parse(xhr.responseText).message; } catch (e) {}
                showAlert('#gen-feedback', msg, 'danger');
            },
            complete: function () {
                $('#btn-generate').prop('disabled', false);
            }
        });
    }

    // ─── PTA Accounts ──────────────────────────────────────────────
    function loadPTAAccounts() {
        ajax({
            data: {action: 'list_pta'},
            success: function (res) {
                var $tb = $('#pta-table tbody').empty();
                if (res.status !== 'success') return;
                $.each(res.data, function (_, p) {
                    $tb.append('<tr>' +
                        '<td>' + p.id + '</td>' +
                        '<td>' + escapeHtml(p.pta_number) + '</td>' +
                        '<td>' + escapeHtml(p.pta_description) + '</td>' +
                        '<td>' + escapeHtml(p.contact_name) + '</td>' +
                        '<td>' + escapeHtml(p.contact_email) + '</td>' +
                        '<td>' + (p.active ? 'Yes' : 'No') + '</td>' +
                        '<td><button class="btn btn-xs btn-outline-primary btn-edit-pta" data-pta=\'' + JSON.stringify(p) + '\'><i class="fas fa-edit"></i></button></td>' +
                        '</tr>');
                });
                // Also refresh the mapping dropdown
                var $sel = $('#map-pta-select').empty().append('<option value="">-- select --</option>');
                $.each(res.data, function (_, p) {
                    if (p.active) {
                        $sel.append('<option value="' + p.id + '" data-number="' + escapeHtml(p.pta_number) + '">' + escapeHtml(p.pta_number) + ' – ' + escapeHtml(p.pta_description) + '</option>');
                    }
                });
            }
        });
    }

    function openPTAForm(data) {
        $('#pta-form-container').show();
        if (data) {
            $('#pta-form-title').text('Edit PTA Account');
            $('#pta-id').val(data.id);
            $('#pta-number').val(data.pta_number);
            $('#pta-description').val(data.pta_description);
            $('#pta-contact-name').val(data.contact_name);
            $('#pta-contact-email').val(data.contact_email);
        } else {
            $('#pta-form-title').text('New PTA Account');
            $('#pta-id').val('');
            $('#pta-number, #pta-description, #pta-contact-name, #pta-contact-email').val('');
        }
    }

    function savePTA() {
        var payload = {
            action: 'save_pta',
            pta_number: $('#pta-number').val(),
            pta_description: $('#pta-description').val(),
            contact_name: $('#pta-contact-name').val(),
            contact_email: $('#pta-contact-email').val(),
            active: 1
        };
        var id = $('#pta-id').val();
        if (id) payload.id = id;
        ajax({
            type: 'POST',
            data: payload,
            success: function (res) {
                if (res.status === 'success') {
                    $('#pta-form-container').hide();
                    loadPTAAccounts();
                } else {
                    alert(res.message || 'Error saving PTA');
                }
            }
        });
    }

    // ─── Mappings ──────────────────────────────────────────────────
    function loadMappings() {
        ajax({
            data: {action: 'get_mappings'},
            success: function (res) {
                var $tb = $('#mapping-table tbody').empty();
                if (res.status !== 'success') return;
                $.each(res.data, function (_, m) {
                    $tb.append('<tr>' +
                        '<td>' + m.id + '</td>' +
                        '<td>' + m.project_id + '</td>' +
                        '<td>' + escapeHtml(m.pta_number) + '</td>' +
                        '<td>' + (m.active ? 'Yes' : 'No') + '</td>' +
                        '<td><button class="btn btn-xs btn-outline-danger btn-remove-mapping" data-id="' + m.id + '"><i class="fas fa-trash"></i></button></td>' +
                        '</tr>');
                });
            }
        });
    }

    function assignPTA() {
        var projectId = $('#map-project-id').val();
        var $opt = $('#map-pta-select option:selected');
        var ptaId = $opt.val();
        var ptaNumber = $opt.data('number');
        if (!projectId || !ptaId) {
            alert('Please fill in both Project ID and PTA Account.');
            return;
        }
        ajax({
            type: 'POST',
            data: {action: 'assign_pta', project_id: projectId, pta_id: ptaId, pta_number: ptaNumber},
            success: function (res) {
                if (res.status === 'success') {
                    loadMappings();
                    $('#map-project-id').val('');
                } else {
                    alert(res.message || 'Error');
                }
            }
        });
    }

    function removeMapping(mappingId) {
        if (!confirm('Remove this PTA mapping?')) return;
        ajax({
            type: 'POST',
            data: {action: 'remove_pta_mapping', mapping_id: mappingId},
            success: function () { loadMappings(); }
        });
    }

    // ─── Toggle icon for accordion ─────────────────────────────────
    $(document).on('show.bs.collapse', '.collapse', function () {
        var $icon = $('[data-target="#' + this.id + '"] .toggle-icon');
        $icon.removeClass('fa-chevron-right').addClass('fa-chevron-down');
    });
    $(document).on('hide.bs.collapse', '.collapse', function () {
        var $icon = $('[data-target="#' + this.id + '"] .toggle-icon');
        $icon.removeClass('fa-chevron-down').addClass('fa-chevron-right');
    });

    // ─── Event Wiring ──────────────────────────────────────────────
    $(document).ready(function () {
        loadReportsList();

        // Tab change – lazy-load
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            var target = $(e.target).attr('href');
            if (target === '#pta-panel') loadPTAAccounts();
            if (target === '#mapping-panel') { loadPTAAccounts(); loadMappings(); }
            if (target === '#reports-panel') loadReportsList();
        });

        // View report drill-down
        $(document).on('click', '.btn-view-report', function () {
            var id    = $(this).data('id');
            var month = $(this).data('month');
            var year  = $(this).data('year');
            viewReport(id, month, year);
        });

        // Back
        $('#btn-back-to-list').on('click', function () {
            $('#report-detail-container').hide();
            $('#reports-list-container').show();
        });

        // Generate
        $('#btn-generate').on('click', generateReport);

        // PTA form
        $('#btn-new-pta').on('click', function () { openPTAForm(null); });
        $('#btn-cancel-pta').on('click', function () { $('#pta-form-container').hide(); });
        $('#btn-save-pta').on('click', savePTA);
        $(document).on('click', '.btn-edit-pta', function () {
            openPTAForm($(this).data('pta'));
        });

        // Mapping
        $('#btn-assign-pta').on('click', assignPTA);
        $(document).on('click', '.btn-remove-mapping', function () {
            removeMapping($(this).data('id'));
        });
    });

})(jQuery);

