<?php

namespace Stanford\ExternalModuleManager;

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';
require_once "emLoggerTrait.php";
require_once "classes/User.php";
require_once "classes/Repository.php";


/**
 * Class ExternalModuleManager
 * @package Stanford\ExternalModuleManager
 */
class ExternalModuleManager extends \ExternalModules\AbstractExternalModule
{

    use emLoggerTrait;


    public function __construct()
    {
        parent::__construct();
        // Other code to run when object is instantiated

        if (isset($_GET['pid'])) {

        }
    }


}
